FROM openjdk:13-jdk-alpine
VOLUME /tmp
COPY target/ConfigServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
COPY src/main/resources/ConfigServer.properties ConfigServer.properties 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","ConfigServer.jar"]